import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../core/api_client.dart';
import '../core/format.dart';
import '../core/labels.dart';
import '../core/models.dart';
import '../core/session.dart';
import '../core/theme.dart';
import '../widgets/common.dart';

/// The intent receipt, generated by the backend from the stored record. Shown after submitting and from history.
class ReceiptScreen extends StatefulWidget {
  const ReceiptScreen({super.key, required this.receipt, this.justSubmitted = false});
  final IntentReceipt receipt;
  final bool justSubmitted;

  @override
  State<ReceiptScreen> createState() => _ReceiptScreenState();
}

class _ReceiptScreenState extends State<ReceiptScreen> {
  late IntentReceipt _r = widget.receipt;
  bool _busy = false;

  Future<void> _cancel() async {
    final l = tr(context);
    final ok = await confirmDialog(context, title: l.cancelConfirmTitle, body: l.cancelConfirmBody, yes: l.yesCancel, no: l.keepPlan, danger: true);
    if (!ok || !mounted) return;
    final api = context.read<ApiClient>(), session = context.read<SessionController>();
    setState(() => _busy = true);
    try {
      final cancelled = await api.cancelIntent(_r.reference);
      session.bump();
      if (mounted) setState(() => _r = cancelled);
    } catch (e) {
      if (mounted) showMessage(context, errorText(l, e));
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final l = tr(context);
    final loc = Localizations.localeOf(context).languageCode;
    final t = Theme.of(context).textTheme;
    final r = _r;
    final cancelled = r.isCancelled;
    return Scaffold(
      appBar: AppBar(title: Text(l.receiptTitle)),
      body: SafeArea(
        child: ListView(padding: const EdgeInsets.all(16), children: [
          const SizedBox(height: 8),
          Center(
            child: CircleAvatar(radius: 40, backgroundColor: cancelled ? AppColors.badSoft : AppColors.goodSoft, child: Icon(cancelled ? Icons.cancel_outlined : Icons.check_rounded, size: 48, color: cancelled ? AppColors.bad : AppColors.good)),
          ),
          const SizedBox(height: 14),
          Semantics(header: true, liveRegion: true, child: Text(cancelled ? l.intentCancelled : l.intentRecorded, textAlign: TextAlign.center, style: t.headlineSmall)),
          const SizedBox(height: 18),
          SectionCard(
            child: Column(children: [
              KeyValueRow(label: l.referenceLabel, value: r.reference, strong: true),
              KeyValueRow(label: l.reviewCycle, value: cycleLabel(r.cycle, loc)),
              KeyValueRow(label: l.reviewFps, value: r.fps.name),
              KeyValueRow(label: l.reviewMode, value: modeLabel(l, r.collectionMode)),
              const Divider(),
              KeyValueRow(label: l.rice, value: l.kgValue(kgText(r.riceKg))),
              KeyValueRow(label: l.wheat, value: l.kgValue(kgText(r.wheatKg))),
              KeyValueRow(label: l.total, value: l.kgValue(kgText(r.totalKg)), strong: true),
              const Divider(),
              KeyValueRow(label: l.submittedOn, value: dateTimeText(r.submittedAt, loc)),
              Padding(
                padding: const EdgeInsets.only(top: 6),
                child: Row(children: [
                  Expanded(child: Text(l.statusLabel, style: t.bodyMedium?.copyWith(color: AppColors.textMuted))),
                  StatusChip(label: intentStatusLabel(l, r.status), tone: cancelled ? Tone.bad : Tone.good, icon: cancelled ? Icons.cancel_outlined : Icons.check_circle_outline),
                ]),
              ),
            ]),
          ),
          const SizedBox(height: 4),
          BigButton(
            label: l.trackMyRation,
            icon: Icons.local_shipping_outlined,
            onPressed: () {
              context.read<TabIndex>().go(1);
              Navigator.of(context).popUntil((route) => route.isFirst);
            },
          ),
          const SizedBox(height: 10),
          if (r.canCancel) ...[
            BigButton(label: l.cancelPlan, icon: Icons.edit_off_outlined, style: BigButtonStyle.danger, onPressed: _busy ? null : _cancel, loading: _busy),
            const SizedBox(height: 10),
          ],
          BigButton(label: l.backToHome, icon: Icons.home_rounded, style: BigButtonStyle.secondary, onPressed: () => Navigator.of(context).popUntil((route) => route.isFirst)),
        ]),
      ),
    );
  }
}
