# Source of truth for the app's UI strings in English, Hindi and Kannada.
# `python tool/gen_arb.py` turns this into lib/l10n/app_*.arb and fails if any language is missing a key or a placeholder.
# Hindi and Kannada are careful first drafts and should be reviewed by native speakers before release.

EN = {
    "appName": "DemandSYNC",
    "appTagline": "Your Ration. Your Rights. Our Priority.",
    "welcomeBody": "A simple, secure and transparent way to plan, track and receive your ration.",
    "getStarted": "Get started",
    "language": "Language",
    "cancel": "Cancel", "confirm": "Confirm", "retry": "Try again", "back": "Back", "close": "Close", "done": "Done",
    "continueBtn": "Continue",
    "kgValue": "{value} kg",
    "dataUnavailable": "Data unavailable",
    "loading": "Loading…",
    # login
    "loginTitle": "Welcome back",
    "loginSubtitle": "Sign in to see your ration details",
    "rationCardLabel": "Ration card number",
    "mobileLabel": "Registered mobile number",
    "sendOtp": "Send OTP",
    "otpTitle": "Enter the OTP",
    "otpSentTo": "We sent a 6-digit code to {mobile}",
    "otpLabel": "6-digit OTP",
    "verifyContinue": "Verify and continue",
    "resendOtp": "Resend OTP",
    "resendIn": "Resend OTP in {seconds}s",
    "devModeBanner": "Development mode: no SMS is sent. Your code is {otp}.",
    "useThisCode": "Use this code",
    "changeNumber": "Change details",
    "fieldRequired": "This field is required",
    "otpInvalidLength": "Enter all 6 digits",
    "loginHelp": "Use the ration card number and mobile number registered with your household.",
    # navigation and greetings
    "navHome": "Home", "navMyRation": "My Ration", "navHistory": "History", "navHelp": "Help",
    "goodMorning": "Good morning", "goodAfternoon": "Good afternoon", "goodEvening": "Good evening",
    # home
    "myPds": "My PDS",
    "currentCycle": "Current cycle",
    "collectionWindow": "Choice window: {start} to {end}",
    "myEntitlement": "My entitlement",
    "rice": "Rice", "wheat": "Wheat", "total": "Total",
    "remaining": "Remaining", "collected": "Collected",
    "currentFps": "My fair price shop",
    "fpsIdLabel": "Shop ID: {id}",
    "openingHours": "Open {hours}",
    "planMyCollection": "Plan my collection",
    "viewMyPlan": "View my plan",
    "trackMyRation": "Track my ration",
    "viewEntitlement": "View entitlement",
    "viewCycle": "About this cycle",
    "rationCardShort": "Ration card {id}",
    "signedInAs": "Signed in",
    # statuses / journey stages (also used as tracking step titles)
    "stChoiceWindowOpen": "Choice window open",
    "stChoiceWindowClosed": "Choice window closed",
    "stIntentSubmitted": "Intent submitted",
    "stDemandPlanned": "Demand planned",
    "stAllocated": "Allocated",
    "stDispatched": "Dispatched",
    "stInTransit": "In transit",
    "stReceivedAtFps": "Received at shop",
    "stAvailableForCollection": "Available for collection",
    "stCollected": "Collected",
    "stateDone": "Done", "stateActive": "In progress", "statePending": "Not yet", "stateDelayed": "On hold",
    "stateUnavailable": "Not available",
    "notYetAvailable": "Not yet available",
    # notices
    "noticePlanNow": "The choice window closes on {closes}. Plan your collection now.",
    "noticeIntentRecorded": "Your plan {ref} is recorded.",
    "noticeRationAtFps": "Your ration has reached your shop. You can collect it.",
    "noticeWindowClosedNoIntent": "The choice window is closed and no plan was submitted for this cycle.",
    "noticeFpsNotActive": "Your shop {fps} is not active right now. Choose another shop when you plan.",
    "noticeNoCycle": "There is no active cycle right now.",
    # entitlement
    "entitlementTitle": "My entitlement",
    "monthlyEntitlement": "Monthly entitlement",
    "alreadyCollected": "Already collected",
    "remainingThisCycle": "Remaining this cycle",
    "schemeLabel": "Scheme",
    "schemeAAY": "Antyodaya (AAY)",
    "schemePHH": "Priority household (PHH)",
    "householdMembers": "{n} members",
    "householdLabel": "Household",
    "entitlementExplain": "Your entitlement is based on your registered household and scheme information.",
    "entitlementReadOnly": "It is set by the government. Your plan can never change it.",
    # cycle
    "cycleTitle": "Current cycle",
    "periodLabel": "Cycle period",
    "windowLabel": "Choice window",
    "statusLabel": "Status",
    "whatThisMeans": "What this means",
    "explainOpen": "You can plan what you want to collect this month. Submit your plan before the window closes.",
    "explainClosedNoPlan": "The window is closed and you did not submit a plan, so nothing was planned for you this cycle.",
    "explainPlanRecorded": "Your plan is recorded. Follow its progress under My Ration.",
    "explainInProgress": "Your ration is moving through the supply chain. Follow it under My Ration.",
    # plan
    "planTitle": "Plan my collection",
    "stepSelect": "Select", "stepReview": "Review", "stepSubmit": "Submit",
    "chooseFps": "Choose your shop",
    "nearestFirst": "Nearest first, in your district",
    "distanceKm": "{km} km away",
    "yourCurrentShop": "Your current shop",
    "shopNotActive": "Not active right now",
    "chooseQuantity": "How much do you want to collect?",
    "riceKg": "Rice (kg)", "wheatKg": "Wheat (kg)",
    "upTo": "Up to {max} kg",
    "collectionMode": "Who will collect?",
    "modeSelf": "I will collect", "modeAuthorized": "Authorized person",
    "calcEntitlement": "Your entitlement", "calcCollected": "Already collected", "calcRemaining": "Remaining",
    "calcRequested": "You are requesting",
    "reviewPlan": "Review plan",
    "enterQuantity": "Choose at least some rice or wheat",
    "increase": "Increase {item}", "decrease": "Decrease {item}",
    "selectedShop": "Selected shop {name}",
    # review
    "reviewTitle": "Review your plan",
    "reviewFps": "Shop", "reviewMode": "Collected by", "reviewCycle": "Cycle",
    "reviewRemainingAfter": "Entitlement left after this plan",
    "reviewWarning": "Please confirm these details before submitting. You cannot change your plan after the choice window closes.",
    "submitIntent": "Submit collection intent",
    "submitting": "Submitting…",
    # receipt
    "intentRecorded": "Collection intent recorded",
    "intentCancelled": "Plan cancelled",
    "referenceLabel": "Reference",
    "submittedOn": "Submitted on",
    "statusRecorded": "Recorded", "statusCancelled": "Cancelled",
    "cancelPlan": "Cancel and change my plan",
    "cancelConfirmTitle": "Cancel this plan?",
    "cancelConfirmBody": "Your plan will be cancelled and you can submit a new one while the window is open.",
    "keepPlan": "Keep my plan", "yesCancel": "Yes, cancel it",
    "backToHome": "Back to home",
    "receiptTitle": "Intent receipt",
    # tracking
    "trackTitle": "Track my ration",
    "journeyOf": "Cycle {cycle}",
    "liveTracking": "Vehicle tracking",
    "vehicleLabel": "Vehicle", "lastUpdate": "Last update", "locationLabel": "Location",
    "routeStop": "Your stop is {n} of {total}",
    "plannedEta": "Planned arrival: about {min} min after departure",
    "liveLocationUnavailable": "LIVE LOCATION UNAVAILABLE",
    "liveLocationUnavailableBody": "The vehicle has not shared a location. Nothing is estimated or made up.",
    "detailNoIntent": "You did not submit a plan for this cycle",
    "detailAllocationOnHold": "Stock for your shop is on hold",
    "detailDeliveryRejected": "The delivery was rejected at the shop and is being resolved",
    "collectedDetail": "Rice {rice} kg, wheat {wheat} kg",
    "cycleData": "Cycle",
    "dataNoteInferred": "Dispatch is confirmed by the delivery record",
    # history
    "historyTitle": "My history",
    "tabCollections": "Collections", "tabTransactions": "Transactions", "tabIntents": "Intents",
    "noHistory": "NO HISTORY AVAILABLE",
    "txnSuccess": "Successful", "txnFailed": "Failed", "txnCancelled": "Cancelled",
    "viewReceipt": "View receipt",
    "transactionsCount": "{n} transactions",
    "atShop": "at {shop}",
    "noReceiptForFailed": "A receipt is only issued for successful collections.",
    # digital receipt
    "digitalReceipt": "Digital receipt",
    "beneficiaryLabel": "Beneficiary",
    "transactionId": "Transaction ID", "receiptNumber": "Receipt number",
    "commodityLabel": "Commodity", "quantityLabel": "Quantity", "dateTimeLabel": "Date and time",
    "verificationRef": "Verification code",
    "scanToVerify": "Show this code at the shop to verify the receipt",
    # help
    "helpTitle": "Help",
    "assistantTitle": "My PDS Assistant",
    "assistantSubtitle": "Ask about your ration, entitlement and status",
    "raiseGrievance": "Raise a grievance",
    "raiseGrievanceSub": "Tell us if something went wrong",
    "myGrievances": "My grievances",
    "signOut": "Sign out",
    "signOutConfirm": "Sign out of DemandSYNC?",
    "helpFooter": "For urgent help, contact your district food office.",
    # assistant
    "assistantHello": "Hello! I can explain your own ration records. What would you like to know?",
    "askPlaceholder": "Ask a question",
    "send": "Send",
    "sourceLabel": "Source: {source}",
    "viewRelated": "View details",
    "assistantNote": "Answers come from your own records. This assistant cannot change anything.",
    "chipEntitlement": "How much can I collect?",
    "chipWindow": "When is my collection window?",
    "chipRequest": "What did I request?",
    "chipDispatch": "Where is my ration?",
    "chipFps": "Which shop am I assigned to?",
    "chipCantSubmit": "Why can't I submit my plan?",
    "assistantThinking": "Checking your records…",
    # grievance
    "grievanceTitle": "Raise a grievance",
    "chooseIssue": "What went wrong?",
    "catShortDelivery": "Short delivery",
    "catWrongQuantity": "Wrong quantity",
    "catFpsIssue": "Shop issue",
    "catQuality": "Quality issue",
    "catTransaction": "Transaction issue",
    "catEntitlement": "Entitlement question",
    "catCollection": "Collection issue",
    "catOther": "Other",
    "describeIssue": "Describe the issue",
    "describeHint": "Write what happened (at least 10 characters)",
    "charCount": "{n} / 500",
    "aiSuggest": "Suggest a category",
    "aiSuggestion": "Suggested: {category}",
    "aiSuggestNote": "This is only a suggestion. You choose before submitting.",
    "useSuggestion": "Use this",
    "aboutTransaction": "About a collection?",
    "noTransactionLink": "Not about a specific collection",
    "submitGrievance": "Submit grievance",
    "grievanceSubmitted": "Grievance submitted",
    "grievanceSubmittedBody": "Your grievance has been recorded. You can follow its status under My grievances.",
    "grStatusOpen": "Open", "grStatusInReview": "In review", "grStatusResolved": "Resolved", "grStatusClosed": "Closed",
    "noGrievances": "You have not raised any grievance",
    "resolutionLabel": "Resolution",
    # errors
    "errOffline": "Unable to connect to PDS services. Please try again.",
    "errTimeout": "The server is taking too long to respond. Please try again.",
    "errServer": "Something went wrong on our side. Please try again in a moment.",
    "errSession": "Your session has expired. Please sign in again.",
    "errGeneric": "Something went wrong. Please try again.",
    "errIntentDuplicate": "Your collection preference has already been submitted for this cycle.",
    "errWindowClosed": "The choice window for this cycle is closed.",
    "errExceedsRemaining": "That is more than your remaining entitlement.",
    "errInvalidQuantity": "Enter a quantity above zero.",
    "errFpsNotEligible": "You can only choose an active shop in your own district.",
    "errNoCycle": "There is no active cycle right now.",
    "errTooMany": "Too many attempts. Please wait a moment and try again.",
    "errBadCredentials": "The details could not be verified. Please check your ration card and mobile number.",
    "errAccountDisabled": "This account is disabled. Please contact the food office.",
    "errOtpUnavailable": "OTP delivery is not available right now. Please try again later.",
    "errNotFound": "We could not find that record.",
    "errOtpInvalid": "Wrong OTP. {left} tries left.",
    "errOtpInvalidLast": "Wrong OTP. Please request a new one.",
    "errOtpExpired": "This OTP has expired. Please request a new one.",
    "errOtpUsed": "This OTP was already used. Please request a new one.",
    "errOtpTooMany": "Too many wrong tries. Please request a new OTP.",
    "errOtpNotRequested": "Please request an OTP first.",
    "errCooldown": "Please wait {seconds}s before asking for another OTP.",
    "sessionExpiredBanner": "Your session expired. Please sign in again.",
}

HI = {
    "appName": "DemandSYNC",
    "appTagline": "आपका राशन। आपका अधिकार। हमारी प्राथमिकता।",
    "welcomeBody": "अपना राशन तय करने, ट्रैक करने और पाने का सरल, सुरक्षित और पारदर्शी तरीका।",
    "getStarted": "शुरू करें",
    "language": "भाषा",
    "cancel": "रद्द करें", "confirm": "पुष्टि करें", "retry": "फिर कोशिश करें", "back": "वापस", "close": "बंद करें", "done": "पूरा हुआ",
    "continueBtn": "आगे बढ़ें",
    "kgValue": "{value} किग्रा",
    "dataUnavailable": "जानकारी उपलब्ध नहीं",
    "loading": "लोड हो रहा है…",
    "loginTitle": "वापसी पर स्वागत है",
    "loginSubtitle": "अपने राशन का विवरण देखने के लिए साइन इन करें",
    "rationCardLabel": "राशन कार्ड नंबर",
    "mobileLabel": "पंजीकृत मोबाइल नंबर",
    "sendOtp": "OTP भेजें",
    "otpTitle": "OTP दर्ज करें",
    "otpSentTo": "हमने {mobile} पर 6 अंकों का कोड भेजा है",
    "otpLabel": "6 अंकों का OTP",
    "verifyContinue": "सत्यापित करें और आगे बढ़ें",
    "resendOtp": "OTP दोबारा भेजें",
    "resendIn": "{seconds} सेकंड में OTP दोबारा भेजें",
    "devModeBanner": "डेवलपमेंट मोड: कोई SMS नहीं भेजा जाता। आपका कोड {otp} है।",
    "useThisCode": "यह कोड उपयोग करें",
    "changeNumber": "विवरण बदलें",
    "fieldRequired": "यह जानकारी आवश्यक है",
    "otpInvalidLength": "सभी 6 अंक दर्ज करें",
    "loginHelp": "अपने परिवार के पंजीकृत राशन कार्ड नंबर और मोबाइल नंबर का उपयोग करें।",
    "navHome": "होम", "navMyRation": "मेरा राशन", "navHistory": "इतिहास", "navHelp": "सहायता",
    "goodMorning": "सुप्रभात", "goodAfternoon": "नमस्कार", "goodEvening": "शुभ संध्या",
    "myPds": "मेरा पीडीएस",
    "currentCycle": "वर्तमान चक्र",
    "collectionWindow": "विकल्प की अवधि: {start} से {end}",
    "myEntitlement": "मेरी पात्रता",
    "rice": "चावल", "wheat": "गेहूँ", "total": "कुल",
    "remaining": "शेष", "collected": "लिया गया",
    "currentFps": "मेरी उचित मूल्य की दुकान",
    "fpsIdLabel": "दुकान आईडी: {id}",
    "openingHours": "खुलने का समय {hours}",
    "planMyCollection": "मेरा संग्रह तय करें",
    "viewMyPlan": "मेरी योजना देखें",
    "trackMyRation": "मेरा राशन ट्रैक करें",
    "viewEntitlement": "पात्रता देखें",
    "viewCycle": "इस चक्र के बारे में",
    "rationCardShort": "राशन कार्ड {id}",
    "signedInAs": "साइन इन",
    "stChoiceWindowOpen": "विकल्प की अवधि खुली है",
    "stChoiceWindowClosed": "विकल्प की अवधि बंद है",
    "stIntentSubmitted": "योजना जमा की गई",
    "stDemandPlanned": "मांग तय हुई",
    "stAllocated": "आवंटित",
    "stDispatched": "भेजा गया",
    "stInTransit": "रास्ते में",
    "stReceivedAtFps": "दुकान पर पहुँचा",
    "stAvailableForCollection": "लेने के लिए उपलब्ध",
    "stCollected": "ले लिया गया",
    "stateDone": "पूरा", "stateActive": "जारी है", "statePending": "अभी नहीं", "stateDelayed": "रुका हुआ",
    "stateUnavailable": "उपलब्ध नहीं",
    "notYetAvailable": "अभी उपलब्ध नहीं",
    "noticePlanNow": "विकल्प की अवधि {closes} को बंद होगी। अभी अपना संग्रह तय करें।",
    "noticeIntentRecorded": "आपकी योजना {ref} दर्ज है।",
    "noticeRationAtFps": "आपका राशन आपकी दुकान पर पहुँच गया है। आप इसे ले सकते हैं।",
    "noticeWindowClosedNoIntent": "विकल्प की अवधि बंद है और इस चक्र के लिए कोई योजना जमा नहीं की गई।",
    "noticeFpsNotActive": "आपकी दुकान {fps} अभी सक्रिय नहीं है। योजना बनाते समय दूसरी दुकान चुनें।",
    "noticeNoCycle": "अभी कोई सक्रिय चक्र नहीं है।",
    "entitlementTitle": "मेरी पात्रता",
    "monthlyEntitlement": "मासिक पात्रता",
    "alreadyCollected": "पहले ही लिया गया",
    "remainingThisCycle": "इस चक्र में शेष",
    "schemeLabel": "योजना",
    "schemeAAY": "अंत्योदय (AAY)",
    "schemePHH": "प्राथमिकता वाला परिवार (PHH)",
    "householdMembers": "{n} सदस्य",
    "householdLabel": "परिवार",
    "entitlementExplain": "आपकी पात्रता आपके पंजीकृत परिवार और योजना की जानकारी पर आधारित है।",
    "entitlementReadOnly": "यह सरकार द्वारा तय है। आपकी योजना इसे कभी नहीं बदल सकती।",
    "cycleTitle": "वर्तमान चक्र",
    "periodLabel": "चक्र की अवधि",
    "windowLabel": "विकल्प की अवधि",
    "statusLabel": "स्थिति",
    "whatThisMeans": "इसका मतलब",
    "explainOpen": "आप इस महीने जो लेना चाहते हैं उसे तय कर सकते हैं। अवधि बंद होने से पहले अपनी योजना जमा करें।",
    "explainClosedNoPlan": "अवधि बंद हो चुकी है और आपने योजना जमा नहीं की, इसलिए इस चक्र में आपके लिए कुछ तय नहीं हुआ।",
    "explainPlanRecorded": "आपकी योजना दर्ज है। इसकी प्रगति मेरा राशन में देखें।",
    "explainInProgress": "आपका राशन आपूर्ति श्रृंखला में आगे बढ़ रहा है। इसे मेरा राशन में देखें।",
    "planTitle": "मेरा संग्रह तय करें",
    "stepSelect": "चुनें", "stepReview": "जाँचें", "stepSubmit": "जमा करें",
    "chooseFps": "अपनी दुकान चुनें",
    "nearestFirst": "आपके जिले में, सबसे नज़दीकी पहले",
    "distanceKm": "{km} किमी दूर",
    "yourCurrentShop": "आपकी वर्तमान दुकान",
    "shopNotActive": "अभी सक्रिय नहीं",
    "chooseQuantity": "आप कितना लेना चाहते हैं?",
    "riceKg": "चावल (किग्रा)", "wheatKg": "गेहूँ (किग्रा)",
    "upTo": "अधिकतम {max} किग्रा",
    "collectionMode": "कौन लेगा?",
    "modeSelf": "मैं लूँगा/लूँगी", "modeAuthorized": "अधिकृत व्यक्ति",
    "calcEntitlement": "आपकी पात्रता", "calcCollected": "पहले ही लिया गया", "calcRemaining": "शेष",
    "calcRequested": "आप माँग रहे हैं",
    "reviewPlan": "योजना जाँचें",
    "enterQuantity": "कम से कम कुछ चावल या गेहूँ चुनें",
    "increase": "{item} बढ़ाएँ", "decrease": "{item} घटाएँ",
    "selectedShop": "चुनी गई दुकान {name}",
    "reviewTitle": "अपनी योजना जाँचें",
    "reviewFps": "दुकान", "reviewMode": "कौन लेगा", "reviewCycle": "चक्र",
    "reviewRemainingAfter": "इस योजना के बाद बची पात्रता",
    "reviewWarning": "जमा करने से पहले कृपया इन विवरणों की पुष्टि करें। विकल्प की अवधि बंद होने के बाद आप अपनी योजना नहीं बदल सकेंगे।",
    "submitIntent": "संग्रह योजना जमा करें",
    "submitting": "जमा हो रहा है…",
    "intentRecorded": "संग्रह योजना दर्ज हो गई",
    "intentCancelled": "योजना रद्द की गई",
    "referenceLabel": "संदर्भ",
    "submittedOn": "जमा करने की तिथि",
    "statusRecorded": "दर्ज", "statusCancelled": "रद्द",
    "cancelPlan": "रद्द करें और योजना बदलें",
    "cancelConfirmTitle": "यह योजना रद्द करें?",
    "cancelConfirmBody": "आपकी योजना रद्द हो जाएगी और अवधि खुली रहने तक आप नई योजना जमा कर सकेंगे।",
    "keepPlan": "योजना रखें", "yesCancel": "हाँ, रद्द करें",
    "backToHome": "होम पर वापस",
    "receiptTitle": "योजना की रसीद",
    "trackTitle": "मेरा राशन ट्रैक करें",
    "journeyOf": "चक्र {cycle}",
    "liveTracking": "वाहन की स्थिति",
    "vehicleLabel": "वाहन", "lastUpdate": "अंतिम अपडेट", "locationLabel": "स्थान",
    "routeStop": "आपकी दुकान {total} में से {n}वीं है",
    "plannedEta": "अनुमानित पहुँच: रवाना होने के लगभग {min} मिनट बाद",
    "liveLocationUnavailable": "लाइव लोकेशन उपलब्ध नहीं",
    "liveLocationUnavailableBody": "वाहन ने अपना स्थान साझा नहीं किया है। कुछ भी अनुमान या बनावटी नहीं दिखाया जाता।",
    "detailNoIntent": "आपने इस चक्र के लिए योजना जमा नहीं की",
    "detailAllocationOnHold": "आपकी दुकान का स्टॉक रुका हुआ है",
    "detailDeliveryRejected": "दुकान पर डिलीवरी अस्वीकार हुई और उसे सुलझाया जा रहा है",
    "collectedDetail": "चावल {rice} किग्रा, गेहूँ {wheat} किग्रा",
    "cycleData": "चक्र",
    "dataNoteInferred": "भेजे जाने की पुष्टि डिलीवरी रिकॉर्ड से हुई",
    "historyTitle": "मेरा इतिहास",
    "tabCollections": "संग्रह", "tabTransactions": "लेन-देन", "tabIntents": "योजनाएँ",
    "noHistory": "कोई इतिहास उपलब्ध नहीं",
    "txnSuccess": "सफल", "txnFailed": "विफल", "txnCancelled": "रद्द",
    "viewReceipt": "रसीद देखें",
    "transactionsCount": "{n} लेन-देन",
    "atShop": "{shop} पर",
    "noReceiptForFailed": "रसीद केवल सफल संग्रह के लिए दी जाती है।",
    "digitalReceipt": "डिजिटल रसीद",
    "beneficiaryLabel": "लाभार्थी",
    "transactionId": "लेन-देन आईडी", "receiptNumber": "रसीद नंबर",
    "commodityLabel": "वस्तु", "quantityLabel": "मात्रा", "dateTimeLabel": "तिथि और समय",
    "verificationRef": "सत्यापन कोड",
    "scanToVerify": "रसीद सत्यापित करने के लिए यह कोड दुकान पर दिखाएँ",
    "helpTitle": "सहायता",
    "assistantTitle": "मेरा पीडीएस सहायक",
    "assistantSubtitle": "अपने राशन, पात्रता और स्थिति के बारे में पूछें",
    "raiseGrievance": "शिकायत दर्ज करें",
    "raiseGrievanceSub": "कुछ गलत हुआ हो तो हमें बताएँ",
    "myGrievances": "मेरी शिकायतें",
    "signOut": "साइन आउट",
    "signOutConfirm": "DemandSYNC से साइन आउट करें?",
    "helpFooter": "तत्काल सहायता के लिए अपने जिला खाद्य कार्यालय से संपर्क करें।",
    "assistantHello": "नमस्ते! मैं आपके अपने राशन रिकॉर्ड समझा सकता हूँ। आप क्या जानना चाहेंगे?",
    "askPlaceholder": "प्रश्न पूछें",
    "send": "भेजें",
    "sourceLabel": "स्रोत: {source}",
    "viewRelated": "विवरण देखें",
    "assistantNote": "उत्तर आपके अपने रिकॉर्ड से आते हैं। यह सहायक कुछ भी बदल नहीं सकता।",
    "chipEntitlement": "मैं कितना ले सकता/सकती हूँ?",
    "chipWindow": "मेरी संग्रह अवधि कब है?",
    "chipRequest": "मैंने क्या माँगा था?",
    "chipDispatch": "मेरा राशन कहाँ है?",
    "chipFps": "मेरी दुकान कौन सी है?",
    "chipCantSubmit": "मैं योजना जमा क्यों नहीं कर पा रहा/रही?",
    "assistantThinking": "आपके रिकॉर्ड देखे जा रहे हैं…",
    "grievanceTitle": "शिकायत दर्ज करें",
    "chooseIssue": "क्या गलत हुआ?",
    "catShortDelivery": "कम मात्रा मिली",
    "catWrongQuantity": "गलत मात्रा",
    "catFpsIssue": "दुकान की समस्या",
    "catQuality": "गुणवत्ता की समस्या",
    "catTransaction": "लेन-देन की समस्या",
    "catEntitlement": "पात्रता का प्रश्न",
    "catCollection": "राशन लेने में समस्या",
    "catOther": "अन्य",
    "describeIssue": "समस्या बताएँ",
    "describeHint": "क्या हुआ लिखें (कम से कम 10 अक्षर)",
    "charCount": "{n} / 500",
    "aiSuggest": "श्रेणी सुझाएँ",
    "aiSuggestion": "सुझाव: {category}",
    "aiSuggestNote": "यह केवल एक सुझाव है। जमा करने से पहले आप ही चुनते हैं।",
    "useSuggestion": "इसे चुनें",
    "aboutTransaction": "किसी संग्रह के बारे में?",
    "noTransactionLink": "किसी विशेष संग्रह के बारे में नहीं",
    "submitGrievance": "शिकायत जमा करें",
    "grievanceSubmitted": "शिकायत जमा हो गई",
    "grievanceSubmittedBody": "आपकी शिकायत दर्ज हो गई है। इसकी स्थिति मेरी शिकायतें में देखें।",
    "grStatusOpen": "खुली", "grStatusInReview": "समीक्षा में", "grStatusResolved": "सुलझी", "grStatusClosed": "बंद",
    "noGrievances": "आपने कोई शिकायत दर्ज नहीं की है",
    "resolutionLabel": "समाधान",
    "errOffline": "पीडीएस सेवाओं से कनेक्ट नहीं हो पा रहा। कृपया फिर कोशिश करें।",
    "errTimeout": "सर्वर जवाब देने में बहुत समय ले रहा है। कृपया फिर कोशिश करें।",
    "errServer": "हमारी ओर से कुछ गड़बड़ हुई। कृपया थोड़ी देर बाद फिर कोशिश करें।",
    "errSession": "आपका सत्र समाप्त हो गया है। कृपया फिर साइन इन करें।",
    "errGeneric": "कुछ गलत हो गया। कृपया फिर कोशिश करें।",
    "errIntentDuplicate": "इस चक्र के लिए आपकी संग्रह पसंद पहले ही जमा हो चुकी है।",
    "errWindowClosed": "इस चक्र के लिए विकल्प की अवधि बंद है।",
    "errExceedsRemaining": "यह आपकी शेष पात्रता से अधिक है।",
    "errInvalidQuantity": "शून्य से अधिक मात्रा दर्ज करें।",
    "errFpsNotEligible": "आप केवल अपने जिले की सक्रिय दुकान चुन सकते हैं।",
    "errNoCycle": "अभी कोई सक्रिय चक्र नहीं है।",
    "errTooMany": "बहुत अधिक प्रयास। कृपया थोड़ी देर रुककर फिर कोशिश करें।",
    "errBadCredentials": "विवरण सत्यापित नहीं हो सके। कृपया अपना राशन कार्ड और मोबाइल नंबर जाँचें।",
    "errAccountDisabled": "यह खाता निष्क्रिय है। कृपया खाद्य कार्यालय से संपर्क करें।",
    "errOtpUnavailable": "OTP भेजने की सुविधा अभी उपलब्ध नहीं है। कृपया बाद में कोशिश करें।",
    "errNotFound": "वह रिकॉर्ड नहीं मिला।",
    "errOtpInvalid": "गलत OTP। {left} कोशिशें बाकी हैं।",
    "errOtpInvalidLast": "गलत OTP। कृपया नया OTP मँगवाएँ।",
    "errOtpExpired": "यह OTP समाप्त हो गया है। कृपया नया OTP मँगवाएँ।",
    "errOtpUsed": "यह OTP पहले ही इस्तेमाल हो चुका है। कृपया नया OTP मँगवाएँ।",
    "errOtpTooMany": "बहुत अधिक गलत कोशिशें। कृपया नया OTP मँगवाएँ।",
    "errOtpNotRequested": "कृपया पहले OTP मँगवाएँ।",
    "errCooldown": "दूसरा OTP माँगने से पहले कृपया {seconds} सेकंड रुकें।",
    "sessionExpiredBanner": "आपका सत्र समाप्त हो गया। कृपया फिर साइन इन करें।",
}

KN = {
    "appName": "DemandSYNC",
    "appTagline": "ನಿಮ್ಮ ಪಡಿತರ. ನಿಮ್ಮ ಹಕ್ಕು. ನಮ್ಮ ಆದ್ಯತೆ.",
    "welcomeBody": "ನಿಮ್ಮ ಪಡಿತರವನ್ನು ಯೋಜಿಸಲು, ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ಪಡೆಯಲು ಸರಳ, ಸುರಕ್ಷಿತ ಮತ್ತು ಪಾರದರ್ಶಕ ಮಾರ್ಗ.",
    "getStarted": "ಪ್ರಾರಂಭಿಸಿ",
    "language": "ಭಾಷೆ",
    "cancel": "ರದ್ದುಮಾಡಿ", "confirm": "ದೃಢೀಕರಿಸಿ", "retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", "back": "ಹಿಂದೆ", "close": "ಮುಚ್ಚಿ", "done": "ಮುಗಿದಿದೆ",
    "continueBtn": "ಮುಂದುವರಿಸಿ",
    "kgValue": "{value} ಕೆಜಿ",
    "dataUnavailable": "ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ",
    "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    "loginTitle": "ಮರಳಿ ಸ್ವಾಗತ",
    "loginSubtitle": "ನಿಮ್ಮ ಪಡಿತರ ವಿವರಗಳನ್ನು ನೋಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "rationCardLabel": "ಪಡಿತರ ಚೀಟಿ ಸಂಖ್ಯೆ",
    "mobileLabel": "ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    "sendOtp": "OTP ಕಳುಹಿಸಿ",
    "otpTitle": "OTP ನಮೂದಿಸಿ",
    "otpSentTo": "ನಾವು {mobile} ಗೆ 6 ಅಂಕಿಯ ಕೋಡ್ ಕಳುಹಿಸಿದ್ದೇವೆ",
    "otpLabel": "6 ಅಂಕಿಯ OTP",
    "verifyContinue": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
    "resendOtp": "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    "resendIn": "{seconds} ಸೆಕೆಂಡ್‌ನಲ್ಲಿ OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
    "devModeBanner": "ಡೆವಲಪ್‌ಮೆಂಟ್ ಮೋಡ್: SMS ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ. ನಿಮ್ಮ ಕೋಡ್ {otp}.",
    "useThisCode": "ಈ ಕೋಡ್ ಬಳಸಿ",
    "changeNumber": "ವಿವರ ಬದಲಿಸಿ",
    "fieldRequired": "ಈ ಮಾಹಿತಿ ಅಗತ್ಯ",
    "otpInvalidLength": "ಎಲ್ಲಾ 6 ಅಂಕಿಗಳನ್ನು ನಮೂದಿಸಿ",
    "loginHelp": "ನಿಮ್ಮ ಕುಟುಂಬದ ನೋಂದಾಯಿತ ಪಡಿತರ ಚೀಟಿ ಸಂಖ್ಯೆ ಮತ್ತು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಬಳಸಿ.",
    "navHome": "ಮುಖಪುಟ", "navMyRation": "ನನ್ನ ಪಡಿತರ", "navHistory": "ಇತಿಹಾಸ", "navHelp": "ಸಹಾಯ",
    "goodMorning": "ಶುಭೋದಯ", "goodAfternoon": "ನಮಸ್ಕಾರ", "goodEvening": "ಶುಭ ಸಂಜೆ",
    "myPds": "ನನ್ನ ಪಿಡಿಎಸ್",
    "currentCycle": "ಪ್ರಸ್ತುತ ಚಕ್ರ",
    "collectionWindow": "ಆಯ್ಕೆ ಅವಧಿ: {start} ರಿಂದ {end}",
    "myEntitlement": "ನನ್ನ ಅರ್ಹತೆ",
    "rice": "ಅಕ್ಕಿ", "wheat": "ಗೋಧಿ", "total": "ಒಟ್ಟು",
    "remaining": "ಉಳಿದಿದೆ", "collected": "ಪಡೆದದ್ದು",
    "currentFps": "ನನ್ನ ನ್ಯಾಯಬೆಲೆ ಅಂಗಡಿ",
    "fpsIdLabel": "ಅಂಗಡಿ ಐಡಿ: {id}",
    "openingHours": "ಸಮಯ {hours}",
    "planMyCollection": "ನನ್ನ ಸಂಗ್ರಹ ಯೋಜಿಸಿ",
    "viewMyPlan": "ನನ್ನ ಯೋಜನೆ ನೋಡಿ",
    "trackMyRation": "ನನ್ನ ಪಡಿತರ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "viewEntitlement": "ಅರ್ಹತೆ ನೋಡಿ",
    "viewCycle": "ಈ ಚಕ್ರದ ಬಗ್ಗೆ",
    "rationCardShort": "ಪಡಿತರ ಚೀಟಿ {id}",
    "signedInAs": "ಸೈನ್ ಇನ್ ಆಗಿದೆ",
    "stChoiceWindowOpen": "ಆಯ್ಕೆ ಅವಧಿ ತೆರೆದಿದೆ",
    "stChoiceWindowClosed": "ಆಯ್ಕೆ ಅವಧಿ ಮುಗಿದಿದೆ",
    "stIntentSubmitted": "ಯೋಜನೆ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    "stDemandPlanned": "ಬೇಡಿಕೆ ನಿಗದಿಯಾಗಿದೆ",
    "stAllocated": "ಹಂಚಿಕೆಯಾಗಿದೆ",
    "stDispatched": "ರವಾನಿಸಲಾಗಿದೆ",
    "stInTransit": "ದಾರಿಯಲ್ಲಿದೆ",
    "stReceivedAtFps": "ಅಂಗಡಿಗೆ ತಲುಪಿದೆ",
    "stAvailableForCollection": "ಪಡೆಯಲು ಲಭ್ಯವಿದೆ",
    "stCollected": "ಪಡೆದಿದ್ದೀರಿ",
    "stateDone": "ಮುಗಿದಿದೆ", "stateActive": "ನಡೆಯುತ್ತಿದೆ", "statePending": "ಇನ್ನೂ ಇಲ್ಲ", "stateDelayed": "ತಡೆಹಿಡಿಯಲಾಗಿದೆ",
    "stateUnavailable": "ಲಭ್ಯವಿಲ್ಲ",
    "notYetAvailable": "ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ",
    "noticePlanNow": "ಆಯ್ಕೆ ಅವಧಿ {closes} ರಂದು ಮುಗಿಯುತ್ತದೆ. ಈಗಲೇ ನಿಮ್ಮ ಸಂಗ್ರಹವನ್ನು ಯೋಜಿಸಿ.",
    "noticeIntentRecorded": "ನಿಮ್ಮ ಯೋಜನೆ {ref} ದಾಖಲಾಗಿದೆ.",
    "noticeRationAtFps": "ನಿಮ್ಮ ಪಡಿತರ ನಿಮ್ಮ ಅಂಗಡಿಗೆ ತಲುಪಿದೆ. ನೀವು ಪಡೆಯಬಹುದು.",
    "noticeWindowClosedNoIntent": "ಆಯ್ಕೆ ಅವಧಿ ಮುಗಿದಿದೆ ಮತ್ತು ಈ ಚಕ್ರಕ್ಕೆ ಯಾವುದೇ ಯೋಜನೆ ಸಲ್ಲಿಸಿಲ್ಲ.",
    "noticeFpsNotActive": "ನಿಮ್ಮ ಅಂಗಡಿ {fps} ಈಗ ಸಕ್ರಿಯವಾಗಿಲ್ಲ. ಯೋಜಿಸುವಾಗ ಬೇರೆ ಅಂಗಡಿಯನ್ನು ಆರಿಸಿ.",
    "noticeNoCycle": "ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ಚಕ್ರ ಇಲ್ಲ.",
    "entitlementTitle": "ನನ್ನ ಅರ್ಹತೆ",
    "monthlyEntitlement": "ಮಾಸಿಕ ಅರ್ಹತೆ",
    "alreadyCollected": "ಈಗಾಗಲೇ ಪಡೆದದ್ದು",
    "remainingThisCycle": "ಈ ಚಕ್ರದಲ್ಲಿ ಉಳಿದಿದೆ",
    "schemeLabel": "ಯೋಜನೆ",
    "schemeAAY": "ಅಂತ್ಯೋದಯ (AAY)",
    "schemePHH": "ಆದ್ಯತಾ ಕುಟುಂಬ (PHH)",
    "householdMembers": "{n} ಸದಸ್ಯರು",
    "householdLabel": "ಕುಟುಂಬ",
    "entitlementExplain": "ನಿಮ್ಮ ಅರ್ಹತೆ ನಿಮ್ಮ ನೋಂದಾಯಿತ ಕುಟುಂಬ ಮತ್ತು ಯೋಜನೆಯ ಮಾಹಿತಿಯ ಮೇಲೆ ಆಧಾರಿತವಾಗಿದೆ.",
    "entitlementReadOnly": "ಇದನ್ನು ಸರ್ಕಾರ ನಿಗದಿಪಡಿಸುತ್ತದೆ. ನಿಮ್ಮ ಯೋಜನೆ ಇದನ್ನು ಎಂದಿಗೂ ಬದಲಿಸಲಾಗದು.",
    "cycleTitle": "ಪ್ರಸ್ತುತ ಚಕ್ರ",
    "periodLabel": "ಚಕ್ರದ ಅವಧಿ",
    "windowLabel": "ಆಯ್ಕೆ ಅವಧಿ",
    "statusLabel": "ಸ್ಥಿತಿ",
    "whatThisMeans": "ಇದರ ಅರ್ಥ",
    "explainOpen": "ಈ ತಿಂಗಳು ನೀವು ಏನು ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ಯೋಜಿಸಬಹುದು. ಅವಧಿ ಮುಗಿಯುವ ಮೊದಲು ಯೋಜನೆ ಸಲ್ಲಿಸಿ.",
    "explainClosedNoPlan": "ಅವಧಿ ಮುಗಿದಿದೆ ಮತ್ತು ನೀವು ಯೋಜನೆ ಸಲ್ಲಿಸಿಲ್ಲ, ಆದ್ದರಿಂದ ಈ ಚಕ್ರದಲ್ಲಿ ನಿಮಗಾಗಿ ಏನೂ ಯೋಜಿಸಲಾಗಿಲ್ಲ.",
    "explainPlanRecorded": "ನಿಮ್ಮ ಯೋಜನೆ ದಾಖಲಾಗಿದೆ. ಅದರ ಪ್ರಗತಿಯನ್ನು ನನ್ನ ಪಡಿತರದಲ್ಲಿ ನೋಡಿ.",
    "explainInProgress": "ನಿಮ್ಮ ಪಡಿತರ ಪೂರೈಕೆ ಸರಪಳಿಯಲ್ಲಿ ಮುಂದುವರಿಯುತ್ತಿದೆ. ಅದನ್ನು ನನ್ನ ಪಡಿತರದಲ್ಲಿ ನೋಡಿ.",
    "planTitle": "ನನ್ನ ಸಂಗ್ರಹ ಯೋಜಿಸಿ",
    "stepSelect": "ಆರಿಸಿ", "stepReview": "ಪರಿಶೀಲಿಸಿ", "stepSubmit": "ಸಲ್ಲಿಸಿ",
    "chooseFps": "ನಿಮ್ಮ ಅಂಗಡಿಯನ್ನು ಆರಿಸಿ",
    "nearestFirst": "ನಿಮ್ಮ ಜಿಲ್ಲೆಯಲ್ಲಿ, ಹತ್ತಿರದ್ದು ಮೊದಲು",
    "distanceKm": "{km} ಕಿಮೀ ದೂರ",
    "yourCurrentShop": "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಅಂಗಡಿ",
    "shopNotActive": "ಈಗ ಸಕ್ರಿಯವಾಗಿಲ್ಲ",
    "chooseQuantity": "ನೀವು ಎಷ್ಟು ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ?",
    "riceKg": "ಅಕ್ಕಿ (ಕೆಜಿ)", "wheatKg": "ಗೋಧಿ (ಕೆಜಿ)",
    "upTo": "ಗರಿಷ್ಠ {max} ಕೆಜಿ",
    "collectionMode": "ಯಾರು ಪಡೆಯುತ್ತಾರೆ?",
    "modeSelf": "ನಾನೇ ಪಡೆಯುತ್ತೇನೆ", "modeAuthorized": "ಅಧಿಕೃತ ವ್ಯಕ್ತಿ",
    "calcEntitlement": "ನಿಮ್ಮ ಅರ್ಹತೆ", "calcCollected": "ಈಗಾಗಲೇ ಪಡೆದದ್ದು", "calcRemaining": "ಉಳಿದಿದೆ",
    "calcRequested": "ನೀವು ಕೇಳುತ್ತಿರುವುದು",
    "reviewPlan": "ಯೋಜನೆ ಪರಿಶೀಲಿಸಿ",
    "enterQuantity": "ಸ್ವಲ್ಪವಾದರೂ ಅಕ್ಕಿ ಅಥವಾ ಗೋಧಿ ಆರಿಸಿ",
    "increase": "{item} ಹೆಚ್ಚಿಸಿ", "decrease": "{item} ಕಡಿಮೆ ಮಾಡಿ",
    "selectedShop": "ಆರಿಸಿದ ಅಂಗಡಿ {name}",
    "reviewTitle": "ನಿಮ್ಮ ಯೋಜನೆ ಪರಿಶೀಲಿಸಿ",
    "reviewFps": "ಅಂಗಡಿ", "reviewMode": "ಯಾರು ಪಡೆಯುವರು", "reviewCycle": "ಚಕ್ರ",
    "reviewRemainingAfter": "ಈ ಯೋಜನೆಯ ನಂತರ ಉಳಿಯುವ ಅರ್ಹತೆ",
    "reviewWarning": "ಸಲ್ಲಿಸುವ ಮೊದಲು ಈ ವಿವರಗಳನ್ನು ದೃಢೀಕರಿಸಿ. ಆಯ್ಕೆ ಅವಧಿ ಮುಗಿದ ನಂತರ ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಬದಲಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    "submitIntent": "ಸಂಗ್ರಹ ಯೋಜನೆ ಸಲ್ಲಿಸಿ",
    "submitting": "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ…",
    "intentRecorded": "ಸಂಗ್ರಹ ಯೋಜನೆ ದಾಖಲಾಗಿದೆ",
    "intentCancelled": "ಯೋಜನೆ ರದ್ದಾಗಿದೆ",
    "referenceLabel": "ಉಲ್ಲೇಖ",
    "submittedOn": "ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ",
    "statusRecorded": "ದಾಖಲಾಗಿದೆ", "statusCancelled": "ರದ್ದಾಗಿದೆ",
    "cancelPlan": "ರದ್ದುಮಾಡಿ ಮತ್ತು ಯೋಜನೆ ಬದಲಿಸಿ",
    "cancelConfirmTitle": "ಈ ಯೋಜನೆಯನ್ನು ರದ್ದುಮಾಡುವುದೇ?",
    "cancelConfirmBody": "ನಿಮ್ಮ ಯೋಜನೆ ರದ್ದಾಗುತ್ತದೆ ಮತ್ತು ಅವಧಿ ತೆರೆದಿರುವಾಗ ನೀವು ಹೊಸದನ್ನು ಸಲ್ಲಿಸಬಹುದು.",
    "keepPlan": "ಯೋಜನೆ ಉಳಿಸಿ", "yesCancel": "ಹೌದು, ರದ್ದುಮಾಡಿ",
    "backToHome": "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    "receiptTitle": "ಯೋಜನೆಯ ರಸೀದಿ",
    "trackTitle": "ನನ್ನ ಪಡಿತರ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "journeyOf": "ಚಕ್ರ {cycle}",
    "liveTracking": "ವಾಹನ ಟ್ರ್ಯಾಕಿಂಗ್",
    "vehicleLabel": "ವಾಹನ", "lastUpdate": "ಕೊನೆಯ ಅಪ್‌ಡೇಟ್", "locationLabel": "ಸ್ಥಳ",
    "routeStop": "ನಿಮ್ಮ ನಿಲ್ದಾಣ {total} ರಲ್ಲಿ {n}",
    "plannedEta": "ಯೋಜಿತ ಆಗಮನ: ಹೊರಟ ಸುಮಾರು {min} ನಿಮಿಷಗಳ ನಂತರ",
    "liveLocationUnavailable": "ಲೈವ್ ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ",
    "liveLocationUnavailableBody": "ವಾಹನ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಂಡಿಲ್ಲ. ಯಾವುದನ್ನೂ ಅಂದಾಜಿಸಿ ಅಥವಾ ಸೃಷ್ಟಿಸಿ ತೋರಿಸಲಾಗುವುದಿಲ್ಲ.",
    "detailNoIntent": "ನೀವು ಈ ಚಕ್ರಕ್ಕೆ ಯೋಜನೆ ಸಲ್ಲಿಸಿಲ್ಲ",
    "detailAllocationOnHold": "ನಿಮ್ಮ ಅಂಗಡಿಯ ಸ್ಟಾಕ್ ತಡೆಹಿಡಿಯಲಾಗಿದೆ",
    "detailDeliveryRejected": "ಅಂಗಡಿಯಲ್ಲಿ ಸರಬರಾಜು ತಿರಸ್ಕೃತವಾಗಿದ್ದು ಬಗೆಹರಿಸಲಾಗುತ್ತಿದೆ",
    "collectedDetail": "ಅಕ್ಕಿ {rice} ಕೆಜಿ, ಗೋಧಿ {wheat} ಕೆಜಿ",
    "cycleData": "ಚಕ್ರ",
    "dataNoteInferred": "ರವಾನೆಯನ್ನು ಸರಬರಾಜು ದಾಖಲೆಯಿಂದ ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    "historyTitle": "ನನ್ನ ಇತಿಹಾಸ",
    "tabCollections": "ಸಂಗ್ರಹಗಳು", "tabTransactions": "ವಹಿವಾಟುಗಳು", "tabIntents": "ಯೋಜನೆಗಳು",
    "noHistory": "ಯಾವುದೇ ಇತಿಹಾಸ ಲಭ್ಯವಿಲ್ಲ",
    "txnSuccess": "ಯಶಸ್ವಿ", "txnFailed": "ವಿಫಲ", "txnCancelled": "ರದ್ದು",
    "viewReceipt": "ರಸೀದಿ ನೋಡಿ",
    "transactionsCount": "{n} ವಹಿವಾಟುಗಳು",
    "atShop": "{shop} ನಲ್ಲಿ",
    "noReceiptForFailed": "ರಸೀದಿಯನ್ನು ಯಶಸ್ವಿ ಸಂಗ್ರಹಗಳಿಗೆ ಮಾತ್ರ ನೀಡಲಾಗುತ್ತದೆ.",
    "digitalReceipt": "ಡಿಜಿಟಲ್ ರಸೀದಿ",
    "beneficiaryLabel": "ಫಲಾನುಭವಿ",
    "transactionId": "ವಹಿವಾಟು ಐಡಿ", "receiptNumber": "ರಸೀದಿ ಸಂಖ್ಯೆ",
    "commodityLabel": "ವಸ್ತು", "quantityLabel": "ಪ್ರಮಾಣ", "dateTimeLabel": "ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
    "verificationRef": "ಪರಿಶೀಲನೆ ಕೋಡ್",
    "scanToVerify": "ರಸೀದಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ಈ ಕೋಡ್ ಅನ್ನು ಅಂಗಡಿಯಲ್ಲಿ ತೋರಿಸಿ",
    "helpTitle": "ಸಹಾಯ",
    "assistantTitle": "ನನ್ನ ಪಿಡಿಎಸ್ ಸಹಾಯಕ",
    "assistantSubtitle": "ನಿಮ್ಮ ಪಡಿತರ, ಅರ್ಹತೆ ಮತ್ತು ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಕೇಳಿ",
    "raiseGrievance": "ದೂರು ಸಲ್ಲಿಸಿ",
    "raiseGrievanceSub": "ಏನಾದರೂ ತಪ್ಪಾದರೆ ನಮಗೆ ತಿಳಿಸಿ",
    "myGrievances": "ನನ್ನ ದೂರುಗಳು",
    "signOut": "ಸೈನ್ ಔಟ್",
    "signOutConfirm": "DemandSYNC ನಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡುವುದೇ?",
    "helpFooter": "ತುರ್ತು ಸಹಾಯಕ್ಕಾಗಿ ನಿಮ್ಮ ಜಿಲ್ಲಾ ಆಹಾರ ಕಚೇರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "assistantHello": "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಸ್ವಂತ ಪಡಿತರ ದಾಖಲೆಗಳನ್ನು ವಿವರಿಸಬಲ್ಲೆ. ನೀವು ಏನು ತಿಳಿಯಲು ಬಯಸುತ್ತೀರಿ?",
    "askPlaceholder": "ಪ್ರಶ್ನೆ ಕೇಳಿ",
    "send": "ಕಳುಹಿಸಿ",
    "sourceLabel": "ಮೂಲ: {source}",
    "viewRelated": "ವಿವರ ನೋಡಿ",
    "assistantNote": "ಉತ್ತರಗಳು ನಿಮ್ಮ ಸ್ವಂತ ದಾಖಲೆಗಳಿಂದ ಬರುತ್ತವೆ. ಈ ಸಹಾಯಕ ಯಾವುದನ್ನೂ ಬದಲಿಸಲಾರದು.",
    "chipEntitlement": "ನಾನು ಎಷ್ಟು ಪಡೆಯಬಹುದು?",
    "chipWindow": "ನನ್ನ ಸಂಗ್ರಹ ಅವಧಿ ಯಾವಾಗ?",
    "chipRequest": "ನಾನು ಏನು ಕೇಳಿದ್ದೆ?",
    "chipDispatch": "ನನ್ನ ಪಡಿತರ ಎಲ್ಲಿದೆ?",
    "chipFps": "ನನ್ನ ಅಂಗಡಿ ಯಾವುದು?",
    "chipCantSubmit": "ನನಗೆ ಯೋಜನೆ ಸಲ್ಲಿಸಲು ಏಕೆ ಆಗುತ್ತಿಲ್ಲ?",
    "assistantThinking": "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…",
    "grievanceTitle": "ದೂರು ಸಲ್ಲಿಸಿ",
    "chooseIssue": "ಏನು ತಪ್ಪಾಯಿತು?",
    "catShortDelivery": "ಕಡಿಮೆ ಪ್ರಮಾಣ ಸಿಕ್ಕಿದೆ",
    "catWrongQuantity": "ತಪ್ಪು ಪ್ರಮಾಣ",
    "catFpsIssue": "ಅಂಗಡಿಯ ಸಮಸ್ಯೆ",
    "catQuality": "ಗುಣಮಟ್ಟದ ಸಮಸ್ಯೆ",
    "catTransaction": "ವಹಿವಾಟಿನ ಸಮಸ್ಯೆ",
    "catEntitlement": "ಅರ್ಹತೆಯ ಪ್ರಶ್ನೆ",
    "catCollection": "ಪಡೆಯುವಲ್ಲಿ ಸಮಸ್ಯೆ",
    "catOther": "ಇತರೆ",
    "describeIssue": "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ",
    "describeHint": "ಏನಾಯಿತು ಎಂದು ಬರೆಯಿರಿ (ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳು)",
    "charCount": "{n} / 500",
    "aiSuggest": "ವರ್ಗವನ್ನು ಸೂಚಿಸಿ",
    "aiSuggestion": "ಸೂಚನೆ: {category}",
    "aiSuggestNote": "ಇದು ಕೇವಲ ಸೂಚನೆ. ಸಲ್ಲಿಸುವ ಮೊದಲು ನೀವೇ ಆರಿಸುತ್ತೀರಿ.",
    "useSuggestion": "ಇದನ್ನು ಬಳಸಿ",
    "aboutTransaction": "ಯಾವುದಾದರೂ ಸಂಗ್ರಹದ ಬಗ್ಗೆಯೇ?",
    "noTransactionLink": "ನಿರ್ದಿಷ್ಟ ಸಂಗ್ರಹದ ಬಗ್ಗೆ ಅಲ್ಲ",
    "submitGrievance": "ದೂರು ಸಲ್ಲಿಸಿ",
    "grievanceSubmitted": "ದೂರು ಸಲ್ಲಿಸಲಾಗಿದೆ",
    "grievanceSubmittedBody": "ನಿಮ್ಮ ದೂರು ದಾಖಲಾಗಿದೆ. ಅದರ ಸ್ಥಿತಿಯನ್ನು ನನ್ನ ದೂರುಗಳಲ್ಲಿ ನೋಡಿ.",
    "grStatusOpen": "ತೆರೆದಿದೆ", "grStatusInReview": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ", "grStatusResolved": "ಪರಿಹರಿಸಲಾಗಿದೆ", "grStatusClosed": "ಮುಚ್ಚಲಾಗಿದೆ",
    "noGrievances": "ನೀವು ಯಾವುದೇ ದೂರು ಸಲ್ಲಿಸಿಲ್ಲ",
    "resolutionLabel": "ಪರಿಹಾರ",
    "errOffline": "ಪಿಡಿಎಸ್ ಸೇವೆಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "errTimeout": "ಸರ್ವರ್ ಪ್ರತಿಕ್ರಿಯಿಸಲು ಬಹಳ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "errServer": "ನಮ್ಮ ಕಡೆಯಿಂದ ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "errSession": "ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    "errGeneric": "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "errIntentDuplicate": "ಈ ಚಕ್ರಕ್ಕೆ ನಿಮ್ಮ ಸಂಗ್ರಹ ಆದ್ಯತೆಯನ್ನು ಈಗಾಗಲೇ ಸಲ್ಲಿಸಲಾಗಿದೆ.",
    "errWindowClosed": "ಈ ಚಕ್ರದ ಆಯ್ಕೆ ಅವಧಿ ಮುಗಿದಿದೆ.",
    "errExceedsRemaining": "ಇದು ನಿಮ್ಮ ಉಳಿದ ಅರ್ಹತೆಗಿಂತ ಹೆಚ್ಚು.",
    "errInvalidQuantity": "ಸೊನ್ನೆಗಿಂತ ಹೆಚ್ಚಿನ ಪ್ರಮಾಣ ನಮೂದಿಸಿ.",
    "errFpsNotEligible": "ನೀವು ನಿಮ್ಮ ಸ್ವಂತ ಜಿಲ್ಲೆಯ ಸಕ್ರಿಯ ಅಂಗಡಿಯನ್ನು ಮಾತ್ರ ಆರಿಸಬಹುದು.",
    "errNoCycle": "ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ಚಕ್ರ ಇಲ್ಲ.",
    "errTooMany": "ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳು. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಕಾಯಿರಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    "errBadCredentials": "ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪಡಿತರ ಚೀಟಿ ಮತ್ತು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
    "errAccountDisabled": "ಈ ಖಾತೆ ನಿಷ್ಕ್ರಿಯವಾಗಿದೆ. ದಯವಿಟ್ಟು ಆಹಾರ ಕಚೇರಿಯನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    "errOtpUnavailable": "OTP ಕಳುಹಿಸುವ ಸೌಲಭ್ಯ ಈಗ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    "errNotFound": "ಆ ದಾಖಲೆ ಸಿಗಲಿಲ್ಲ.",
    "errOtpInvalid": "ತಪ್ಪು OTP. {left} ಪ್ರಯತ್ನಗಳು ಉಳಿದಿವೆ.",
    "errOtpInvalidLast": "ತಪ್ಪು OTP. ದಯವಿಟ್ಟು ಹೊಸದನ್ನು ವಿನಂತಿಸಿ.",
    "errOtpExpired": "ಈ OTP ಅವಧಿ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಹೊಸದನ್ನು ವಿನಂತಿಸಿ.",
    "errOtpUsed": "ಈ OTP ಅನ್ನು ಈಗಾಗಲೇ ಬಳಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಹೊಸದನ್ನು ವಿನಂತಿಸಿ.",
    "errOtpTooMany": "ತುಂಬಾ ತಪ್ಪು ಪ್ರಯತ್ನಗಳು. ದಯವಿಟ್ಟು ಹೊಸ OTP ವಿನಂತಿಸಿ.",
    "errOtpNotRequested": "ದಯವಿಟ್ಟು ಮೊದಲು OTP ವಿನಂತಿಸಿ.",
    "errCooldown": "ಇನ್ನೊಂದು OTP ಕೇಳುವ ಮೊದಲು ದಯವಿಟ್ಟು {seconds} ಸೆಕೆಂಡ್ ಕಾಯಿರಿ.",
    "sessionExpiredBanner": "ನಿಮ್ಮ ಸೆಷನ್ ಮುಗಿದಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
}
